### ISSUE TITLE
Hasil UAT (1)

### ISSUE THREAD

**Issue by DeddyChandra** [DeddyChandra/simpendak#1]
# Hasil UAT (gagal)

## User
- [x] Melakukan cuti tenaga kependidikan
- [x] Membatalkan pengajuan cuti
- [x] Edit biodata
- [ ] Login gagal
- [x] Login berhasil tapi tidak aktivitasi

## KSP
- [x] Melihat dan menulis catatan hitam
- [x] Catatan hitam pada kepegawaian tidak ada

## Yayasan
- [x] Penugasan pegawai (Jabatan tidak perlu dimasukkan dalam pilihan penugasan)
- [x] Pengangkatan tetap (Error saat melakukan validasi pengangkatan pegawai tetap)
- [x] Kenaikan pangkat (Data pegawai yang akan naik pangkat tidak tertampil pada KSP untuk proses persetujuan)
- [x] Proses pengunduran pegawai (Pengisian form pengunduran diri dari BACKEND outputnya kemana? pengunduran diri tidak tampil di sisi Backend maupun KSP. Pengunduran diri hanya diajukan oleh pegawai bersangkutan)
- [x] Pengangkatan Tetap (Data pegawai yang difollowup ke KSP tidak tampil dan proses tidak berjalan)
- [x] Kenaikan Pangkat (Data pegawai yang difollow up ke KSP tidak tampil dari proses tidak berjalan)
- [x] Kenaikan berkala (Data pegawai yang difollow up ke KSP tidak tampil dari proses tidak berjalan)
- [x] Penyesuain gaji pegawai (Data pegawai yang di follow up ke KSP tidak tampil dari proses tidak berjalan, sebaliknya pegawai yang menerima kenaikan berkala tidak ditampilkan)
- [x] Cuti melahirkan (Data dari pengajuan cuti pegawai tidak bisa direkam karena ada error)
- [x] Pengunduran diri (Data pengajuan cuti pegawai tidak bisa direkam karena ada error)
- [x] Konfigurasi sistem (Kadang membuka dialog konfigurasi error, error menambahkan data konfigurasi)
- [x] Reset cuti (Dialog konfigurasi sistem error)
- [x] Menghapus user (semua user dianggap builtin)  https://github.com/DeddyChandra/simpendak/issues/2#issue-1176933681

## Screenshot
- [x] yang ditampilkan NIKnya saja  https://github.com/DeddyChandra/simpendak/issues/3#issue-1176935943
- [x] error saat membuka menu konfigurasi
- [x] logout blank https://github.com/DeddyChandra/simpendak/issues/4#issue-1176944141
- [x] tombol approval item pegawai yang sudah disable aktif kembali jika ada item dengan nip yang sama aktif
- [x] kenaikan berkala https://github.com/DeddyChandra/simpendak/issues/5#issue-1176963209
- [x] Pegawai kenaikan pangkat bisa berturut turut dalam waktu yang bersamaan https://github.com/DeddyChandra/simpendak/issues/6#issue-1176982415
- [x] error validasi kenaikan pangkat https://github.com/DeddyChandra/simpendak/issues/5#issue-1176963209
- [x] error persetujuan penyesuain gaji https://github.com/DeddyChandra/simpendak/issues/5#issue-1176963209
- [x] terdapat tanggal lahir pada satuan pendidikan di `/administrasi/mutasi` https://github.com/DeddyChandra/simpendak/issues/7#issue-1176986905
- [x] pesan validasi kenaikan pangkat tidak sesuai https://github.com/DeddyChandra/simpendak/issues/8#issue-1177073393
- [x] filter satuan pendidikan tidak berfungsi semua data tampil
- [x] tampil karakter `z` pada tambah user login https://github.com/DeddyChandra/simpendak/issues/9#issue-1177079560
- [x] laporan tidak tampil 
- [x] konfirmasi password tidak sama padahal password sudah sama https://github.com/DeddyChandra/simpendak/issues/10#issue-1177106403
- [ ] tampilan dashboard kurang rapi

## Notes:
1. untuk kenaikan pangkat, pegawai tetap, kenaikan berkala dll, setiap user hanya diproses di salah satu , dan ketika user tersebut telah di approve maka user tersebut dapat di followup lagi di kenaikan pangkat, pegawai tetap, kenaikan berkala dll

**Comment by DeddyChandra** [comment]
> # Hasil UAT (gagal)
> ## User
> * [ ]  Melakukan cuti tenaga kependidikan
> * [ ]  Membatalkan pengajuan cuti
> * [ ]  Edit biodata
> * [ ]  Login gagal
> * [ ]  Login berhasil tapi tidak aktivitasi
> 
> ## KSP
> * [ ]  Melihat dan menulis catatan hitam
> * [ ]  Catatan hitam pada kepegawaian tidak ada
> 
> ## Yayasan
> * [ ]  Penugasan pegawai (Jabatan tidak perlu dimasukkan dalam pilihan penugasan)
> * [ ]  Pengangkatan tetap (Error saat melakukan validasi pengangkatan pegawai tetap)
> * [ ]  Kenaikan pangkat (Data pegawai yang akan naik pangkat tidak tertampil pada KSP untuk proses persetujuan)
> * [ ]  Proses pengunduran pegawai (Pengisian form pengunduran diri dari BACKEND outputnya kemana? pengunduran diri tidak tampil di sisi Backend maupun KSP. Pengunduran diri hanya diajukan oleh pegawai bersangkutan)
> * [ ]  Pengangkatan Tetap (Data pegawai yang difollowup ke KSP tidak tampil dan proses tidak berjalan)
> * [ ]  Kenaikan Pangkat (Data pegawai yang difollow up ke KSP tidak tampil dari proses tidak berjalan)
> * [ ]  Kenaikan berkala (Data pegawai yang difollow up ke KSP tidak tampil dari proses tidak berjalan)
> * [ ]  Penyesuain gaji pegawai (Data pegawai yang di follow up ke KSP tidak tampil dari proses tidak berjalan, sebaliknya pegawai yang menerima kenaikan berkala tidak ditampilkan)
> * [ ]  Cuti melahirkan (Data dari pengajuan cuti pegawai tidak bisa direkam karena ada error)
> * [ ]  Pengunduran diri (Data pengajuan cuti pegawai tidak bisa direkam karena ada error)
> * [ ]  Konfigurasi sistem (Kadang membuka dialog konfigurasi error, error menambahkan data konfigurasi)
> * [ ]  Reset cuti (Dialog konfigurasi sistem error)
> * [ ]  Menghapus user (semua user dianggap builtin)
> 
> ## Screenshot
> * [ ]  yang ditampilkan NIKnya saja
> * [ ]  error saat membuka menu konfigurasi
> * [ ]  logout blank
> * [ ]  tombol approval item pegawai yang sudah disable aktif kembali jika ada item dengan nip yang sama aktif
> * [ ]  kenaikan berkala
> * [ ]  Pegawai kenaikan pangkat bisa berturut turut dalam waktu yang bersamaan
> * [ ]  error validasi kenaikan pangkat
> * [ ]  error persetujuan penyesuain gaji
> * [ ]  pesan validasi kenaikan pangkat tidak sesuai
> * [ ]  filter satuan pendidikan tidak berfungsi semua data tampil
> * [ ]  tampil karakter `z` pada tambah user login
> * [ ]  laporan tidak tampil
> * [ ]  konfirmasi password tidak sama padahal password sudah sama
> * [ ]  tampilan dashboard kurang rapi

**Comment by DeddyChandra** [comment]
> ## User
> * [x]  Melakukan cuti tenaga kependidikan
> * [x]  Membatalkan pengajuan cuti

Melakukan cuti tenaga kerja error dikarenakan status login sebagai guru sehingga tidak ada opsi untuk melakukan cuti pegawai

**Comment by DeddyChandra** [comment]
> ## User
> - [x] Edit biodata

Dikarenakan fitur di disable oleh Backend

**Comment by DeddyChandra** [comment]
> ## KSP
> - [ ] Melihat dan menulis catatan hitam
> - [ ] Catatan hitam pada kepegawaian tidak ada

Setelah saya coba bisa dan ada catatan hitam (mungkin orang yang test tidak melihat button kuning untuk membuat catatan hitam, dan KSP lainnya berhasil

**Comment by DeddyChandra** [comment]
> ## Yayasan
> - [X] Penugasan pegawai (Jabatan tidak perlu dimasukkan dalam pilihan penugasan)

Tambah jabatan baru pada database `tidak ada jabatan`

**Comment by DeddyChandra** [comment]
> ## Yayasan
> - [X] Kenaikan pangkat (Data pegawai yang akan naik pangkat tidak tertampil pada KSP untuk proses > persetujuan)

Berhasil followup keniakan pangkat dan tampil di ksp 

### Backend
![image](https://user-images.githubusercontent.com/57496224/159500371-b6222c18-5572-4738-8f75-8bb68dc38989.png)


### KSP
![image](https://user-images.githubusercontent.com/57496224/159500545-f251753c-5baf-4d64-bc8a-8ab9e414cccb.png)

![image](https://user-images.githubusercontent.com/57496224/159500653-157959d3-2433-4027-a561-f41bc86b88da.png)

**Comment by DeddyChandra** [comment]
> ## Yayasan
> - [X] Proses pengunduran pegawai (Pengisian form pengunduran diri dari BACKEND outputnya kemana? > pengunduran diri tidak tampil di sisi Backend maupun KSP. Pengunduran diri hanya diajukan oleh > pegawai bersangkutan)

Disisi user langsung mendapatkan status keluar
![image](https://user-images.githubusercontent.com/57496224/159502088-1a1d383c-6afd-40a7-b7ce-6f169fac082e.png)

**Comment by DeddyChandra** [comment]
> ## Yayasan
> - [X] Pengangkatan Tetap (Data pegawai yang difollowup ke KSP tidak tampil dan proses tidak > berjalan)

## Backend
Proses followup berhasil
![image](https://user-images.githubusercontent.com/57496224/159505590-1db60c91-4bf1-464a-bba6-0264b6683449.png)


## KSP
![image](https://user-images.githubusercontent.com/57496224/159505851-a576cb25-97e6-4303-bf3c-372fc55ad0b2.png)

![image](https://user-images.githubusercontent.com/57496224/159505937-e719d538-ddd8-4361-911f-507460600d23.png)


## Backend
![image](https://user-images.githubusercontent.com/57496224/159506213-566a7150-1307-437c-b7d0-19d4a579afc5.png)

![image](https://user-images.githubusercontent.com/57496224/159506327-a17dab8c-8110-4ef4-88f5-b0fff9a868c0.png)

**Comment by DeddyChandra** [comment]
> ## Yayasan Screenshot
> - [X] tombol approval item pegawai yang sudah disable aktif kembali jika ada item dengan nip yang sama aktif

![image](https://user-images.githubusercontent.com/57496224/159508062-2c7aadec-9129-44c8-b0be-f4104ba0251c.png)

**Comment by DeddyChandra** [comment]
> ## Yayasan
> - [X] Kenaikan berkala (Data pegawai yang difollow up ke KSP tidak tampil dari proses tidak > berjalan)

## Backend
![image](https://user-images.githubusercontent.com/57496224/159508703-4cdf1286-ae01-4e54-8d82-d80eca0494d8.png)


## KSP
![image](https://user-images.githubusercontent.com/57496224/159508815-fd365d46-34c6-4609-ad82-688d54f83f3d.png)

![image](https://user-images.githubusercontent.com/57496224/159508877-8c5c264a-ed90-449a-b164-7ab56b8ff7a3.png)


## Backend
![image](https://user-images.githubusercontent.com/57496224/159509050-c4a0fe34-20fd-4534-9116-799ff8f9c8c7.png)
![image](https://user-images.githubusercontent.com/57496224/159509144-d0696cef-727e-4093-9934-46f13b6320f7.png)

**Comment by DeddyChandra** [comment]
> ## Yayasan
> - [X] Pengunduran diri (Data pengajuan cuti pegawai tidak bisa direkam karena ada error)

## User
![image](https://user-images.githubusercontent.com/57496224/159512551-8f8292f5-945d-4e3c-ae21-2bf9d6ad243b.png)

## Backend
![image](https://user-images.githubusercontent.com/57496224/159512688-a9216620-7da9-4993-b3ef-851a9f972205.png)

**Comment by DeddyChandra** [comment]
> ## Yayasan
> - [X] Konfigurasi sistem (Kadang membuka dialog konfigurasi error, error menambahkan data > konfigurasi)
> - [X] Reset cuti (Dialog konfigurasi sistem error)

Dikarenakan ada kesalahan value pada database sehingga terjadi error, ( `stat = 0` sehingga di anggap config tersebut tidak aktif)
setiap ada config baru, config sebelumnya semua akan di set menjadi `0`

**Comment by DeddyChandra** [comment]
>

**Comment by DeddyChandra** [comment]
> ## Screenshot
> - [X] error saat membuka menu konfigurasi 

ref : https://github.com/DeddyChandra/simpendak/issues/1#issuecomment-1075295771

**Comment by DeddyChandra** [comment]
> ## Yayasan Screenshot
> - [X] laporan tidak tampil

Laporan tampil di localhost maupun di server chandra.click https://simpendak.chandra.click/backend/laporan/datapegawai/print

Gimana caranya masuk ke state laporan kosong? (atau waktu itu datanya belum di isi)
